# Generated by Django 4.2 on 2026-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='实收金额')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='找零')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('member', '会员卡')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('paid', '已支付'), ('refunded', '已退款'), ('canceled', '已取消'), ('suspend', '挂起')], default='paid', max_length=20, verbose_name='订单状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'orderitem',
            },
        ),
        migrations.CreateModel(
            name='SuspendedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(verbose_name='购物车内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='挂单时间')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('status', models.IntegerField(choices=[(1, '挂单中'), (2, '已取单')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '挂单',
                'verbose_name_plural': '挂单',
                'db_table': 'suspendedcart',
            },
        ),
    ]
