# Generated by Django 4.2 on 2026-03-15 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
        ('members', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspendedcart',
            name='cashier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收银员'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='收银员'),
        ),
        migrations.AddField(
            model_name='order',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='会员'),
        ),
        migrations.AddIndex(
            model_name='suspendedcart',
            index=models.Index(fields=['cashier'], name='suspendedca_cashier_72f6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='suspendedcart',
            index=models.Index(fields=['status'], name='suspendedca_status_e06236_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orderitem_order_i_75ec43_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orderitem_product_3ca469_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='order_order_n_4c2cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['create_time'], name='order_create__939187_idx'),
        ),
    ]
