# Generated by Django 4.2 on 2026-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=30, unique=True, verbose_name='会员卡号')),
                ('name', models.CharField(max_length=100, verbose_name='会员姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='储值余额')),
                ('level', models.CharField(default='普通', max_length=20, verbose_name='会员等级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_visit_time', models.DateTimeField(blank=True, null=True, verbose_name='最后消费时间')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'db_table': 'member',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='member_phone_c3a7e4_idx'),
        ),
    ]
