# Generated by Django 4.2 on 2026-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('manual', '手动备份'), ('auto', '自动备份')], max_length=20, verbose_name='备份类型')),
                ('file_name', models.CharField(max_length=255, verbose_name='备份文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='备份文件路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='备份状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='备份时间')),
            ],
            options={
                'verbose_name': '备份日志',
                'verbose_name_plural': '备份日志',
                'db_table': 'backup_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('manual', '手动备份'), ('auto', '定期备份')], default='manual', max_length=20, verbose_name='备份策略')),
                ('backup_period', models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='备份周期')),
                ('enable_captcha', models.BooleanField(default=True, verbose_name='启用登录验证码')),
                ('system_name', models.CharField(default='零售店POS系统', max_length=100, verbose_name='系统名称')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '系统设置（扩展）',
                'verbose_name_plural': '系统设置（扩展）',
                'db_table': 'systemsettings',
            },
        ),
    ]
