# Generated by Django 4.2 on 2026-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='赠送积分'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='threshold_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='满额金额(元)'),
        ),
    ]
