# Generated by Django 4.2 on 2026-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('level', models.IntegerField(default=1, verbose_name='分类级别')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='条形码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='零售价')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='成本价')),
                ('stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('warning_stock', models.IntegerField(default=5, verbose_name='预警库存')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('status', models.BooleanField(default=True, verbose_name='上架状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('sale', '销售出库'), ('purchase', '采购入库'), ('return', '退货入库'), ('adjust', '盘点调整')], max_length=20, verbose_name='变动类型')),
                ('quantity', models.IntegerField(verbose_name='变动数量')),
                ('before_stock', models.IntegerField(verbose_name='变动前库存')),
                ('after_stock', models.IntegerField(verbose_name='变动后库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='变动时间')),
            ],
            options={
                'verbose_name': '库存日志',
                'verbose_name_plural': '库存日志',
                'db_table': 'stocklog',
            },
        ),
    ]
