# Generated by Django 4.2 on 2026-03-15 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='operator',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='products.category', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='父分类'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['product'], name='stocklog_product_c6ceca_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['order'], name='stocklog_order_i_d33d75_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['operator'], name='stocklog_operato_8f5bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['create_time'], name='stocklog_create__b57c55_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_d2887e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categor_26b384_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='category_parent__869b08_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level'], name='category_level_e67701_idx'),
        ),
    ]
