# Generated by Django 4.2 on 2026-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='保质期(天)'),
        ),
    ]
